### ISSUE TITLE
Breaking change not propery documented

### ISSUE THREAD

**Issue by stefanheine** [thenativeweb/nodeenv#3]
Hi, in your latest change you changed the interface:
https://github.com/thenativeweb/nodeenv/commit/8f66da014d8f3c95148a7e903fafdbdd834e2cd0

nodeenv 0.2.1: 
```javascript
nodeenv({
   NODE_ENV: 'dev'
}, function (restore) {
  // ...
  restore();
});
```

nodeenv 0.3.0:
 ```javascript
const restore = nodeenv({
   NODE_ENV: 'dev'
});
```

that's a pretty breaking change that should be properly documented in a new major version!

**Comment by goloroden** [comment]
Yes, and I'm sorry for the issues that you had because of this 😢 

The reason why we didn't increase the major version number is that we are still on a pre-`1.0.0`-release here, and for that, semver does not require this. Although I have to admit that it would have been helpful if you had known that …

**Comment by stefanheine** [comment]
well... when are you going to make it 1.0.0 then? the module hadn't been updated for ~2 years... so it seems pretty mature. (but looking at your list of modules, you seem to be very reluctant in making something 1.x... 5 of 99). knowing this I'll be a lot more careful with your updates... ;(

could you still document breaking changes then, even for 0.x upgrades, please.

**Comment by goloroden** [comment]
We currently do not have any plans on turning this into a `1.0.0` version, but I get your point. We'll think about this and find a solution for this in the future. 😊
